config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/input',   to: 'static_pages#input'
  get  '/about',   to: 'static_pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class IncorrectSexError < NoMethodError; end

class String
  # select caseで書けばよかった
  def to_japanese_sex
    if self == 'male'
      '男'
    elsif self == 'female'
      '女'
    else
      raise IncorrectSexError 'incorrect sex'
    end
  end
end

class StaticPagesController < ApplicationController
  def home
    # begin
    # メソッド頭なのでbeginは省略可
    @jpn_sex = params[:sex].to_japanese_sex
    @birthday = Date.new(params[:birthday][:year].to_i, params[:birthday][:month].to_i, params[:birthday][:day].to_i)
  rescue StandardError #=> e
    # puts e.message
    # puts e.backtrace.inspect
    redirect_to input_path
    # end # beginの対
  end

  # def input
  # end

  # def about
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def full_title(page_title = '')
  #   base_title = "LIMIT | 余命計算機"
  #   if page_title.empty?
  #     base_title
  #   else
  #     base_title + " | " + page_title
  #   end
  # end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def full_title(page_title = '')
    base_title = 'LIMIT | 余命計算機'
    if page_title.empty?
      base_title
    else
      base_title + ' | ' + page_title
    end
  end

  TOKYO_TIMEZONE = 9 * 60 * 60

  def my_age_year(birthday, arg_now = Time.now.getlocal(TOKYO_TIMEZONE))
    # 年齢表示機能用、整数部分だけで切り捨て
    # 日付を一度文字列→整数にして引き、年齢の整数部分を出す
    # raise 'type assert' unless arg_now.class == Time
    (arg_now.strftime('%Y%m%d').to_i - birthday.strftime('%Y%m%d').to_i) / 10_000
  end

  # https://www.mhlw.go.jp/toukei/saikin/hw/life/22th/index.html
  # 平成27年
  AVERAGE_ONE_YEAR_SECOND = 365.2425 * 24 * 60 * 60 # うるう年を計算すると一年は365.2425日

  def rest_of_life_sec(birthday, sex, arg_now = Time.now.getlocal(TOKYO_TIMEZONE))
    age_sec = arg_now - birthday.to_time
    raise 'incorrect arg_age' unless age_sec.between?(-2 * AVERAGE_ONE_YEAR_SECOND, 97 * AVERAGE_ONE_YEAR_SECOND)

    if sex == '男'
      (-0.767 * age_sec + 74.5 * AVERAGE_ONE_YEAR_SECOND).to_i
    elsif sex == '女'
      (-0.814 * age_sec + 81.7 * AVERAGE_ONE_YEAR_SECOND).to_i
    else
      raise 'incorrect sex'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      body {
        background-color: black;
        color: aqua;
      }
    </style>
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P&display=swap" rel="stylesheet">
</head>

  <body>
    <div class="centering">
      <h1 class="pixel_font">LIMIT</h1>
      <%= yield %>
      <div class="right_bottom">
        <%= link_to "このサイトについて", about_path %>
      </div>  
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "このサイトについて") %>

<h3 class = "pink">
  Q1.このサイト何？
</h3>
<p>
  A1.性別と誕生日から、余命の秒数を計算します。表示方法は日付とカウントダウンの二種類です。
</p>
<p>
  ホームページに設定して、ネットでの時間浪費対策などに。
</p>
<h3 class = "pink">
  Q2.余命の計算方法は？
</h3>
<p>
  A2.厚生労働省が出している第22回完全生命表の、平均余命の数値を単回帰分析しました。
</p>
<p>
  このサイトの推定余命は30歳〜95歳の人はやや楽観的、それ以外ではやや悲観的に算出されています。
</p>
<h3 class = "pink">
  Q3.リロードしたら、推定寿命が伸びてるんだけど？
</h3>
<p>
  A3.簡単に言うと「あなたと同じ誕生日で、たった今亡くなってしまった人」が外れたためです。
</p>
<p>
  例えば「日本人全員」の平均寿命は80代ですが、「100年以上生きてる日本人だけ」の平均寿命は102歳くらい。
</p>
<p>
  これは「100歳まで生きられなかった日本人」が除外されたためです。
</p>
<h3 class = "pink">
  Q4.これカウント0まで待ったらどうなるの？
</h3>
<p>
  A4.何の機能も作ってません。多分マイナスに突入すると思います。
</p>



<%= link_to :back do %>
  <button>戻る</button>
<% end %>

app/views/static_pages/home.html.erb
<% rest_second = rest_of_life_sec @birthday, @jpn_sex %>
<% time_limit = Time.now + rest_second %>
<p>
  <%= "#{my_age_year @birthday}歳#{@jpn_sex}性のあなたの推定タイムリミットは#{time_limit.strftime("%Y年%-m月%-d日")}です。" %>
</p>
<p>
  推定タイムアップまで残り
</p>
<p>
  <h2 id="myTimer", class="pixel_font"><%= rest_second %>sec</h1>
</p>
<%= link_to "誕生日、性別を再入力する", input_path , class: "btn btn-light rounded-pill btn-lg" %>

app/views/static_pages/input.html.erb
<% provide(:title, "入力画面") %>

<%= form_tag("/", method: "get", class: "text-center h6") do %>
<div class="horizon_container">
  生年月日：
  <%= select_date Date.new, 
    prefix: :birthday,
    use_month_numbers: true,
    start_year: Date.today.year - 95,
    end_year: Date.today.year %>
</div>
<div class="horizon_container ">
  性別：
  <%= radio_button_tag(:sex, "male") %>
  <%= label_tag(:sex, "男性") %>
  <%= radio_button_tag(:sex, "female") %>
  <%= label_tag(:sex, "女性") %>
</div>

<%= submit_tag "決定", name: nil, class: "btn btn-light rounded-pill btn-lg" %>
<% end %>